# Generated by Django 4.2.7 on 2023-11-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customermanager', '0001_initial'),
        ('addressmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='customermanager.customer'),
            preserve_default=False,
        ),
    ]
