# Generated by Django 4.2.7 on 2023-11-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customermanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('net_value_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_value_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brut_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customermanager.customer')),
            ],
        ),
    ]
