# Generated by Django 4.2.7 on 2023-11-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='brut_total',
            new_name='gross_total',
        ),
        migrations.AddField(
            model_name='entry',
            name='cart',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='cartmanager.cart'),
            preserve_default=False,
        ),
    ]
