# Generated by Django 4.2.7 on 2023-11-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartmanager', '0002_rename_brut_total_cart_gross_total_entry_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='gross_total',
            new_name='cart_gross_total',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='net_total',
            new_name='cart_net_total',
        ),
    ]
